//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TestUDL.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TESTUDL_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDC_BTN_OPEN                    1000
#define IDC_EDIT1                       1001
#define IDC_EDIT_TLS_VALUE              1001
#define IDC_EDIT_TLS_WAV                1001
#define IDC_BTN_SETTING_WL              1002
#define IDC_BTN_READ_PM                 1003
#define IDC_EDIT2                       1004
#define IDC_EDIT_PM_CHANNEL             1004
#define IDC_EDIT_TLS_CHANNEL            1005
#define IDC_BTN_TLS_POWER               1006
#define IDC_BTN_TLS_ENABLE              1007
#define IDC_BTN_TLS_UNIT                1008
#define IDC_BTN_TLS_PARAMETERS          1009
#define IDC_BTN_PM_WL                   1010
#define IDC_EDIT_PM_VALUE               1011
#define IDC_EDIT_PM_WAV                 1011
#define IDC_BTN_PM_UNIT                 1012
#define IDC_BTN_PM_RANGE                1013
#define IDC_BTN_PM_AVGTIME              1014
#define IDC_BTN_PM_PARAMTER             1015
#define IDC_EDIT_VOA_CHANNEL            1016
#define IDC_EDIT_VOA_VALUE              1017
#define IDC_BTN_VOA_WL                  1018
#define IDC_BTN_VOA_ATTEN               1019
#define IDC_BTN_VOA_READ_WL             1020
#define IDC_BTN_VOA_READ_ATTEN          1021
#define IDC_CHECK1                      1022
#define IDC_CHECK_OPENCOH               1022
#define IDC_EDIT_TLS_VALUE2             1023
#define IDC_EDIT_TLS_POWER              1023
#define IDC_EDIT_TLS_VALUE3             1024
#define IDC_EDIT_TLS_UNIT               1024
#define IDC_BTN_OSA_SETRBW              1025
#define IDC_EDIT_OSA_CH                 1026
#define IDC_BTN_OSA_INIT                1027
#define IDC_BTN_OSA_RESET               1028
#define IDC_BTN_OSA_CLOSE               1029
#define IDC_CHECK_OPEN                  1030
#define IDC_BTN_OSA_GETRBW              1031
#define IDC_EDIT_OSA_RBW                1032
#define IDC_EDIT_OSA_CH_COUNT           1033
#define IDC_EDIT_OSA_WAV                1034
#define IDC_EDIT_OSA_GAIN               1035
#define IDC_EDIT_OSA_SNR                1036
#define IDC_BTN_OSA_LCMODE              1037
#define IDC_BTN_OSA_SCAN                1038
#define IDC_BTN_OSA_SCANZOOM            1039
#define IDC_BTN_OSA_NF                  1040
#define IDC_BTN_PM_RANGE2               1041
#define IDC_EDIT_OSA_POWER              1042
#define IDC_EDIT_OSA_OFFSET             1043
#define IDC_EDIT_OSA_WAV2               1044
#define IDC_EDIT_OSA_MSG                1045
#define IDC_BTN_OSA_CHCOUNT             1046
#define IDC_BTN_OSA_POWER               1047
#define IDC_BTN_OSA_SNR                 1048
#define IDC_BTN_OSA_GAIN                1049
#define IDC_BTN_OSA_WAV                 1050
#define IDC_BTN_OSA_SETOFFSET           1051
#define IDC_BTN_OSA_GETOFFSET           1052
#define IDC_BTN_OSA_ZOOM_RESULT         1053
#define IDC_BTN_OSA_SCAN_RESULT         1054
#define IDC_BTN_OSA_RUN                 1055
#define IDC_BTN_OSA_SAVE                1056
#define IDC_BUTTON18                    1057
#define IDC_BTN_OSA_GETDATAONCE         1058
#define IDC_BTN_OSA_GETDATA             1059
#define IDC_BTN_OSA_MSG                 1060
#define IDC_BTN_TLS_CLOSE               1061
#define IDC_BTN_TLS_MSG                 1062
#define IDC_EDIT_TLS_MSG                1063
#define IDC_EDIT_PM_UNIT                1064
#define IDC_EDIT_PM_TIME                1065
#define IDC_EDIT_PM_POWER               1066
#define IDC_EDIT_PM_MSG                 1067
#define IDC_BTN_PM_ZERO                 1068
#define IDC_BTN_PM_MSG                  1069
#define IDC_EDIT_VOA_MSG                1070
#define IDC_CHECK_VOA_ENABLE            1071
#define IDC_BTN_VOA_OFFSET              1072
#define IDC_BTN_VOA_CLOSE               1073
#define IDC_BTN_VOA_RESET               1074
#define IDC_BTN_VOA_MSG                 1075
#define IDC_BTN_VOA_STATE               1076
#define IDC_EDIT_PM_RANGE               1077
#define IDC_EDIT_OSA_POINT              1078
#define IDC_CHECK_OURZOOM               1079
#define IDC_EDIT_OSA_SRCOFFSET          1080
#define IDC_BTN_OSA_INITSINGLESCAN      1081
#define IDC_BTN_CLOSE                   1082
#define IDC_EDIT_POL_MSG                1083
#define IDC_BTN_POL_POLAZIER            1084
#define IDC_BTN_POL_POLAZIER2           1085
#define IDC_BTN_POL_POLAZIER3           1086
#define IDC_EDIT_POL_ANGLE              1087
#define IDC_EDIT_CHAMBER_TEMP           1088
#define IDC_EDIT_POL_MSG2               1089
#define IDC_BTN_CHAMBER_SETTEP          1090
#define IDC_BTN_CHAMBER_GETSETTEMP      1091
#define IDC_BTN_CHAMBER_CURRENT_TEMP    1092
#define IDC_BTN_POL_GetPOLAZIER         1093
#define IDC_EDIT_POL_CHANNEL            1094
#define IDC_BUTTON1                     1095
#define IDC_BTN_COMTEST                 1095
#define IDC_EDIT_CHAMBER_CHANNEL        1096
#define IDC_BTN_PM_GETWL                1097
#define IDC_BTN_PM_GETUNIT              1098
#define IDC_BTN_PM_GETAVGTIME           1099
#define IDC_BTN_CLOSECOM                1100
#define IDC_BTN_OPENCOM                 1101
#define IDC_BTN_PM_OFFSET               1102
#define IDC_BTN_PM_OFFSET2              1103
#define IDC_BTN_PM_MAXMIN               1103

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1096
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
